import React, { useMemo } from 'react'
import { ArrowRight, BriefcaseBusiness, GraduationCap, MapPin, Route, Sparkles } from 'lucide-react'
import { Link } from 'react-router-dom'
import OpportunityCard from '../components/opportunities/OpportunityCard'
import FitSummary from '../components/common/FitSummary'
import { opportunities, getDistanceKm } from '../services/opportunityService'
import { getProfile } from '../services/profileService'
import { matchProfileToOpportunity } from '../services/matchingService'
import MapCanvas from '../components/common/MapCanvas'

export default function Dashboard({ profile = getProfile() }) {
  const nearby = useMemo(() => opportunities.filter((item) => getDistanceKm(item) <= 25), [])
  const recommended = useMemo(() => nearby.map((item) => ({ item, match: matchProfileToOpportunity(profile, item) })).sort((a, b) => b.match.matchPercentage - a.match.matchPercentage).slice(0, 4), [nearby, profile])
  const allMatches = nearby.map((item) => matchProfileToOpportunity(profile, item))
  const skills = [...new Set(allMatches.flatMap((match) => match.missingSkills))]
  const strongest = Math.round(allMatches.reduce((sum, match) => sum + match.matchPercentage, 0) / Math.max(allMatches.length, 1))
  return <section className="dashboard-page section"><div className="container"><div className="dashboard-hero"><div><div className="eyebrow"><Sparkles size={13} /> Your student dashboard</div><h1>Welcome back.</h1><p><MapPin size={15} /> {profile.location || 'Panaji, Goa'}</p></div><div className="dashboard-profile-summary"><strong>{profile.education} · {profile.year}</strong><span>Profile strength {strongest}%</span></div></div><section className="dashboard-section"><div className="section-head-row"><div><div className="eyebrow">Your next moves</div><h2>Small steps, <em>real options.</em></h2></div></div><div className="next-moves"><Link to="/jobs"><BriefcaseBusiness size={19} /><span><b>Jobs you could explore</b><small>{nearby.filter((item) => item.type === 'Job').length} nearby roles</small></span><ArrowRight size={16} /></Link><Link to="/colleges"><GraduationCap size={19} /><span><b>Colleges you may qualify for</b><small>{nearby.filter((item) => item.type === 'College').length} nearby options</small></span><ArrowRight size={16} /></Link><Link to="/paths"><Route size={19} /><span><b>Skills you should learn next</b><small>{skills.slice(0, 2).join(' · ') || 'Keep exploring'}</small></span><ArrowRight size={16} /></Link></div></section><section className="dashboard-section"><div className="section-head-row"><div><div className="eyebrow">Opportunities near you</div><h2>See what’s <em>around.</em></h2></div><Link className="arrow-link" to="/explore">Explore the map <ArrowRight size={14} /></Link></div><div className="dashboard-map">  <MapCanvas items={nearby.slice(0, 7)} profile={profile} zoomable /></div></section><section className="dashboard-section"><div className="section-head-row"><div><div className="eyebrow">Recommended for you</div><h2>Worth a <em>closer look.</em></h2></div></div><div className="dashboard-cards">{recommended.map(({ item }) => <OpportunityCard item={item} profile={profile} key={item.id} />)}</div></section><section className="dashboard-skill-section"><FitSummary matchPercentage={strongest} status={strongest >= 75 ? 'eligible' : strongest >= 60 ? 'almost' : 'explore'} matchedSkills={profile.skills} missingSkills={skills.slice(0, 4)} message="Your matches improve as you keep learning and updating your profile." /><Link className="button button-ghost" to="/paths">View my paths <ArrowRight size={15} /></Link></section></div></section>
}
